networks:
  app_net:
    external: true

services:
  frontend:
    image: frontend:${DOCKER_TAG:-prod}
    container_name: frontend
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks: [app_net]
    restart: unless-stopped
