version: "3.8"

networks:
  app_net:
    external: true

services:
  frontend:
    build:
      context: .
      target: production
    container_name: frontend
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    networks: [app_net]
    restart: unless-stopped
